### PR TITLE
Persist into pgsql

### PR DESCRIPTION
**Pull request by fcamblor**
Introduced `Sequelize` ORM allowing to fetch & persist data using both `sqlite` (default) or `postgresql`.

It allows to workaround cloud PaaS habit (like heroku) to delete the whole nodejs server when hibernating (note that even with some "pinging" workaround making the app always up, heroku introduced some limitation since June 1st where [free dynos could not run over 18h a day without sleeping](https://devcenter.heroku.com/articles/free-dyno-hour-faq#why-is-heroku-changing-how-free-dynos-work-what-are-the-changes))

With this PR, you can now configure a postgresql datasource using `DB_CONNECTION_URL` environment variable and persist your data into a Postgresql database (like a free one from https://elephantsql.com)
That way, even if your NodeJS app content is cleant, data will remain.

### CODE REVIEW

**Comment by christocracy** [comment]
I *will* have a look at this some time :)

**Comment by christocracy** [comment]
This PR is obsolete since I've completely refactored the app using latest React and Redux

**Comment by fcamblor** [comment]
@christocracy will it be worth to try to make another PR with my changes here (introducing `Sequelize` ORM to abstract db persistence layer and allow to make it compatible to pgsql db) but applied on the newly refactored code ?

Don't want to spend time for nothing

**Comment by christocracy** [comment]
Yes, it should be fine.  It should be more pleasant to work with now that I've separated everything out of one monolithic `server.js`.

**Comment by fcamblor** [comment]
Done in #23 :-)

**Pull request closed without merging**
