### PR TITLE
Persist in pgsql after refacto

### PR DESCRIPTION
**Pull request by fcamblor**
This is a follow up of #18 and compatible with recent refactoring
> Introduced Sequelize ORM allowing to fetch & persist data using both sqlite (default) or postgresql.
> 
> It allows to workaround cloud PaaS habit (like heroku) to delete the whole nodejs server when hibernating (note that even with some "pinging" workaround making the app always up, heroku introduced some limitation since June 1st where free dynos could not run over 18h a day without sleeping)
> 
> With this PR, you can now configure a postgresql datasource using DB_CONNECTION_URL environment variable and persist your data into a Postgresql database (like a free one from https://elephantsql.com)
> That way, even if your NodeJS app content is cleant, data will remain.

Note that this branch is in the prolongation of #22 (if you merge #22, I'll rebase this branch over `master` branch)

### CODE REVIEW

**Comment by christocracy** [comment]
Thanks

**Comment by christocracy** [comment]
```
Executing (default): SELECT `id`, `uuid`, `device_id`, `device_model`, `latitude`, `longitude`, `accuracy`, `altitude`, `speed`, `heading`, `odometer`, `event`, `activity_type`, `activity_confidence`, `battery_level`, `battery_is_charging`, `is_moving`, `geofence`, `provider`, `extras`, `recorded_at`, `created_at` FROM `locations` AS `locations` WHERE `locations`.`recorded_at` BETWEEN '2017-04-06T04:00:56.434Z' AND '2017-05-02T03:59:56.434Z' AND `locations`.`device_id` = 'Cordova-a76924c11115eb8b' ORDER BY recorded_at DESC;
Executing (default): SELECT `device_id`, `device_model` FROM `locations` AS `locations` GROUP BY `device_id`, `device_model` ORDER BY max(recorded_at) DESC;
Uncaught error :  { TypeError: date.indexOf is not a function
    at DATE.parse (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/lib/dialects/sqlite/data-types.js:28:14)
    at /Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/lib/dialects/sqlite/query.js:170:36
    at /Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/node_modules/lodash/lodash.js:12666:23
    at /Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.mapValues (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/node_modules/lodash/lodash.js:12665:7)
    at /Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/lib/dialects/sqlite/query.js:134:32
    at Array.map (native)
    at Statement.afterExecute (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/lib/dialects/sqlite/query.js:133:39)
--> in Database#all('SELECT `id`, `uuid`, `device_id`, `device_model`, `latitude`, `longitude`, `accuracy`, `altitude`, `speed`, `heading`, `odometer`, `event`, `activity_type`, `activity_confidence`, `battery_level`, `battery_is_charging`, `is_moving`, `geofence`, `provider`, `extras`, `recorded_at`, `created_at` FROM `locations` AS `locations` WHERE `locations`.`recorded_at` BETWEEN \'2017-04-06T04:00:56.434Z\' AND \'2017-05-02T03:59:56.434Z\' AND `locations`.`device_id` = \'Cordova-a76924c11115eb8b\' ORDER BY recorded_at DESC;', [], [Function: afterExecute])
    at /Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/lib/dialects/sqlite/query.js:241:36
    at Promise._execute (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:79:10)
    at executeSql (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/sequelize/lib/dialects/sqlite/query.js:103:19)
    at tryCatcher (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/chris/Documents/workspace/transistor/tmp/background-geolocation-console/node_modules/bluebird/js/release/promise.js:614:10) __augmented: true }
```

**Comment by christocracy** [comment]
Wait.  It worked after I deleted my `background-geolocation.db` from previous PR.

**Comment by fcamblor** [comment]
OK, so it means the sequelize migration would not work with existing data ?
I didn't tested this case

**Comment by christocracy** [comment]
Yes, it pukes on old database.  Not a huge issue, since my refactor wasn't compatible with the old schema either.

Seems to be a problem with `recorded_at`

```
Executing (default): SELECT `device_id`, `device_model` FROM `locations` AS `locations` GROUP BY `device_id`, `device_model` ORDER BY max(recorded_at) DESC;
```

**Pull request merged**
