### PR TITLE
(WIP) UI changes, async/await, etc...

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
Test PR, still work in progress.

### CODE REVIEW

**Comment by christocracy** [comment]
```
$ rm -rf node_modules
$ npm install
$ npm run server

ford-2:background-geolocation-console chris$ npm run server

> background-geolocation-console@2.0.0 server /Users/chris/Documents/workspace/transistor/background-geolocation-console
> babel-node server.js

Uncaught error :  TypeError: Cannot read property 'bold' of undefined
    at Server.<anonymous> (/Users/chris/Documents/workspace/transistor/background-geolocation-console/server.js:47:15)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1284:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Function.Module.runMain (module.js:606:11)
    at Object.<anonymous> (/Users/chris/Documents/workspace/transistor/background-geolocation-console/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

**Comment by christocracy** [comment]
You seem to have remove [`colors`](https://github.com/transistorsoft/background-geolocation-console/blob/master/server.js#L4) from `server.js`

**Comment by christocracy** [comment]
```
$ git log

commit e5f733d514d51edb585d290559e82844df6a6faf
Author: ZeusTheTrueGod <l-2732@yandex.ru>
Date:   Sun Jun 25 18:50:26 2017 +0300

    moving server side code to latest babel, adding explicit async/await for DB operations
```

```
$ rm -rf node_modules
$ npm install
$ npm run server

> background-geolocation-console@2.0.0 server /Users/chris/Documents/workspace/transistor/background-geolocation-console
> babel-node server.js

module.js:471
    throw err;
    ^

Error: Cannot find module './src/server/database/initializeDatabase'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chris/Documents/workspace/transistor/background-geolocation-console/server.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/chris/Documents/workspace/transistor/background-geolocation-console/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/chris/Documents/workspace/transistor/background-geolocation-console/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by christocracy** [comment]
When removing points > 1000, don't remove points having where `event` is present in data (eg: `event: "motionchange"`, `event: "geofence"`)

**Comment by ZeusTheTrueGod** [comment]
Good idea! Right now I keep those which have a geofence associated.

**Comment by ZeusTheTrueGod** [comment]
Done

**Pull request merged**
